### ISSUE TITLE
[test] Compare CerebVascularReact CO2_inahalation pipeline to AMIGO

### ISSUE THREAD

**Issue by manuegrx** [populse/mia_processes#41]
Compare CerebVascularReact CO2_inahalation pipeline to AMIGO --> check on subject Alej

**Comment by manuegrx** [comment]
Comparison done on subject test alej170316 using the common physio regressor (not the individual one). 

There are differences in the results obtain with MIA compare to the one obtains with AMIGO. 
The beta image are not exactly the same (different pixel values but they are close) 

If we are looking the preprocessing data, they do not have exactly the same pixel values (see norm anat, smoothed func and mean func), so beta images can not be exactly the same 

![AMIGOvsMIA_alej](https://github.com/populse/mia_processes/assets/47973414/0baa73b2-8eb8-429b-a80e-690a71c2be81)
(in this figure left : AMIGO and right: MIA) 

Possible explanations: 
- conversion to NIfTI done in a different way in MIA and AMIGO so the input data of the process are not  exactly the same 
- spm version is maybe not the same and it can also add little differences during preprocessing 

Next step: 
- if possible : get the input func and anat data in NIFTI used in AMIGO and used them in MIA 
- if possible: get the preprocessing data in AMIGO (smoothed func, deformation field and native class images) and used them in MIA 
- check spm version

**Comment by manuegrx** [comment]
Version of SPM / matlab used for AMIGO (MAC) : spm12 (6409 2015-04-16 not standalone ) and matlab2015 

Two different tests have been done:

### Used T1 and functional data from AMIGO in MIA
For T1, "alej_test_std_anat_001.nii" image has been used. The image has been first reoriented using `as_reoriented` function from nibabel ( `t1.as_reoriented(np.array([[0, -1],[1, -1], [2, 1]])). 

For functional data , the images "alej_test_std_hypc12_***.nii" have been concatenated with `concat_images` from nibabel (with `check_affines=False`) and the output image has been reoriented as the T1. 

For both data, voxel values are not the same as the one obtained with the conversion used in MIA (with mriconv).

Oriented data have been used as input for the C02_inhalation pipeline. 

Result obtained in MIA are different from the result from AMIGO &rarr;  differences in  NIfTI conversion are not the only explanation 


### Used the preprocessed images from AMIGO in MIA 
We use AMIGO's smoothed functional data, the realgments parameters and the mask_002  in MIA.
For smoothed functional data, the "swralej_test_std_hypc12_***.nii" images have been concatenated with `concat_images` from nibabel.
C02_inhalation pipeline was adapted to remove all preprocessing: 
![image](https://github.com/populse/mia_processes/assets/47973414/2be50a06-ce84-49c1-831f-d9c1e05daeae)

Voxel values of the beta images obtained with MIA are really close to the one obtained with AMIGO but they are not exactly the same &rarr;  it could be due either the SPM version (and Matlab) ( or maybe to to a difference in default parameters for level one design brick)

![image](https://github.com/populse/mia_processes/assets/47973414/67534572-26f6-4d20-8dd0-5744d4312d2a)

### TO DO 
If the differences are explained only be the differences in the conversion and by SPM/matlab version, it seems to be useful to evaluate the impact on several subjects. 
It will be easier with the final report , so I propose to wait for this report before to continuing the comparison.

Maybe it will be also useful to check all the default parameters

**Comment by servoz** [comment]
With the same SPM, Matlab (License), general parameters (CVR_Reg == 'physio', Mov_Reg == 'Y', Art_Reg == 'N' in Amigo) for Mia and Amigo.

Impact of conversion.

- Comparison of intensity values for the same voxels in data converted in Mia and Amigo (using MRIcron).
    - Anat:
         -  (I_amigo - I_mia) / average Intensities, seems to be less than 1% (careful, done on only a few voxels, therefore to be taken only as a trend).
    - Func:
        - 1st dynamic: (I_amigo - I_mia) / average of intensities, seems to be less than 0.5% (caution, carried out on a few voxels only, so only to be taken as a trend).
    - So there's a slight difference in intensity after conversion in Amigo and Mia (no difference visible to the naked eye). Does this difference have a real impact on the result (the GLM incorporates the variation inherent in any statistical measurement, so we can legitimately ask ourselves this question)?
    - To address the question of the impact of differences generated during conversion, the initial data were converted in Amigo and then analyzed within Mia. The results obtained are virtually identical whether the data were converted using Mia or Amigo.
![gaucheRegularinMia_droitedatafromAmigo](https://github.com/populse/mia_processes/assets/37933899/a34c7da9-f7a6-49a5-a06a-1f38309c90c7)
  - As a reminder, here is the reference result obtained in Amigo (the target to be approached):
![RegularAmigo](https://github.com/populse/mia_processes/assets/37933899/1ea9696e-68a3-4f48-b2fb-05260f5ea4a3)


The main difference with the target lies in the middle cerebral artery. Could there be an issue with the mask? To ensure accuracy, we will need to review and compare all the steps, and perhaps give more attention to mask production.

**Comment by servoz** [comment]
- 1_spatial_preprocessing pipeline: completed.

At this stage of the investigation, two differences remain:

- The difference resulting from the conversion to NIfTI format. We will assess in the final synthesis whether it is necessary to use the exact same conversion method (and who is correct? Amigo or Mia?). An important limitation is that `mri_conv`, the tool responsible for the conversion in Mia, is third-party software (though hosted in populse), and the response time of the mri_conv developer can be lengthy.

- Segmentation utilizes non-default values for the `warp.mrf`, `warp.cleanup`, and `warp.fwhm` parameters. These parameters inevitably lead to differences, albeit minor. However, nipype does not provide these parameters. We will evaluate whether these parameters are necessary in Mia during the final synthesis.

**Comment by servoz** [comment]
- 2_spatial_mask pipeline: completed.

**Comment by servoz** [comment]
After an in-depth study of the pipeline and the bricks that make it up, we were able to fix a number of issues, and today we have a result that is very close to that achieved at Amigo.

As an example, we can see that the IL from GLM are very similar and are now perfectly within the uncertainty range of the method:
![Mia2](https://github.com/populse/mia_processes/assets/37933899/ddf062e0-e3a2-45ef-8f24-2c397b2ce039)
![Amigo2](https://github.com/populse/mia_processes/assets/37933899/9e0e9751-a3ca-4253-8f23-70d113feadf7)

A few differences remain, but these have been explained and can be corrected if necessary. In my opinion, at this stage, these differences do not influence the result sufficiently to make it a priority to implement changes that could lead to their removal.

These are:
- The data conversion performed in Amigo does not give exactly the same result as the one performed in Mia (mri_conv).
- Amigo uses correction parameters not available in nipype for segmentation `warp.mrf`, `warp.cleanup` and `warp.fwhm`. The result is a very slight difference.
- At the end of pre-processing or GLM analysis, there are very slight differences in the data produced, without explanation ... I would have liked to go even further and see exactly how the final system call is handled by nipype. I didn't do it because, given the current result, I don't think it's a priority. But we should be aware that the results are not perfectly identical (very slight differences) with SPM via nipype compared with SPM directly.

We can ask ourselves whether these differences are more an improvement or a reduction in the quality of the data. At this stage I'm unable to say. Maybe the results in Mia are better than in Amigo ... or not!

The tests were carried out with a standard regressor (not the patient's) and without using ART (Artifact Detection Tools).

I think this ticket can now be closed. There are still a few things to be sorted out in the automatic report, but another ticket already exists for that (#67).
