### ISSUE TITLE
[bug] report - True Type font version issue on Mac 

### ISSUE THREAD

**Issue by manuegrx** [populse/mia_processes#83]
We installed populse mia on a Mac (the light version not using casa distro, python 3.9 is used) and there is an issue during report creation in the CVR pipeline (but it is not specif to the CVR pipeline, I think we will get the same issue with an other pipeline that create a report" ). 

The True Type font version is not recognized by reportlab at [the begging of the report creation ](https://github.com/populse/mia_processes/blob/master/mia_processes/utils/report.py#L101)

```
 Traceback (most recent call last):
 [...]
  File "/Volumes/Workspace/MIA/sources/mia_processes/mia_processes/bricks/reports/reporting.py", line 1544, in run_process_mia
    report = Report(
  File "/Volumes/Workspace/MIA/sources/mia_processes/mia_processes/utils/report.py", line 102, in __init__
    TTFont(
  File "/Volumes/Workspace/PYENV/mia-env/lib/python3.9/site-packages/reportlab/pdfbase/ttfonts.py", line 1192, in __init__
    self.face = TTFontFace(filename, validate=validate, subfontIndex=subfontIndex)
  File "/Volumes/Workspace/PYENV/mia-env/lib/python3.9/site-packages/reportlab/pdfbase/ttfonts.py", line 1073, in __init__
    TTFontFile.__init__(self, filename, validate=validate, subfontIndex=subfontIndex)
  File "/Volumes/Workspace/PYENV/mia-env/lib/python3.9/site-packages/reportlab/pdfbase/ttfonts.py", line 439, in __init__
    TTFontParser.__init__(self, file, validate=validate,subfontIndex=subfontIndex)
  File "/Volumes/Workspace/PYENV/mia-env/lib/python3.9/site-packages/reportlab/pdfbase/ttfonts.py", line 176, in __init__
    isCollection = self.readHeader()
  File "/Volumes/Workspace/PYENV/mia-env/lib/python3.9/site-packages/reportlab/pdfbase/ttfonts.py", line 242, in readHeader
    raise TTFError('Not a recognized TrueType font: version=0x%8.8X' % version)

reportlab.pdfbase.ttfonts.TTFError: Not a recognized TrueType font: version=0x76657273
```

The ttf file read by reportlab is the [one store](https://github.com/populse/mia_processes/blob/master/mia_processes/utils/DejaVuSans.ttf) in MIA process. 

On Linux, I do not have this issue as the version of the file read by reportlab is `0x00010000` (version recognized by reportlab) . On Mac, the version read by reportlab is `0x76657273` and it not one of the recognized version. 

For now I do not understand why the version is not the same on Mac and Linux

**Comment by servoz** [comment]
Is it running from an IDE (or a virtual env)  of directly from the host ?

The error you're encountering suggests that the DejaVuSans.ttf (`os.path.join(os.path.dirname(__file__), "DejaVuSans.ttf"`) file might be handled differently between the Linux and macOS environments, even though it's the same file. This can occur due to differences in how file systems handle encoding or file metadata.

if I remember correctly the file comes from a linux system, I've never tried it with a macos system. We should try to find the equivalent file on the macos system you're using and use it to check that it's not a compatibility problem (just point it by hard-coding first, just to check in the line):
```
pdfmetrics.registerFont(
            TTFont(
                "DejaVuSans",
                os.path.join(os.path.dirname(__file__), "DejaVuSans.ttf"),
            )
        )

```
Also check the version of reportlab, in short, anything that could mean that the file is not recognised or compatible.

Another possibility, I don't know if it's managed by git LSF. The file in question is there? it's not an empty file that hasn't been fed by git LFS ? (for example on my linux sytem) :

```
/mia_processes/mia_processes/utils $ ls -lh 
total 980K
-rw-rw-r--. 1 econdami econdami 740K Apr 30 17:19 DejaVuSans.ttf
-rw-rw-r--. 1 econdami econdami 1010 Jul  5 16:58 __init__.py
drwxrwxr-x. 2 econdami econdami 4.0K Jun 14 11:12 __pycache__
-rw-rw-r--. 1 econdami econdami 194K Jul  5 16:58 report.py
-rw-rw-r--. 1 econdami econdami  36K Jul  5 16:58 tools.py
```

**Comment by manuegrx** [comment]
Thank you for your tips, it was an issue with the size of the file. I did not use `git lfs clone ` to clone the repository because on Linux system it is not necessary but it seems that for Mac it is (I also had an issue with the logo image, they were not fully downloaded). 

One year ago, I updated the populse mia documentation to remove the use of lfs because it was written that  ""git lfs clone" has been deprecated since Git LFS 2.3.0. From this version, use "git clone" command directly ".  I will try` git lsf clone ` on the Mac and see if it works, if yes I will update the documentation.
